server:
  port: 8080

spring:
  application:
    name: killua-dashboard
  
  datasource:
    url: jdbc:h2:mem:killua_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            redirect-uri: ${DISCORD_REDIRECT_URI}
            scope: identify,email
            authorization-grant-type: authorization_code
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in milliseconds

# Logging
logging:
  level:
    dev.killua.dashboard: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# External API Configuration
external:
  api:
    base-url: ${EXTERNAL_API_BASE_URL:https://api.killua.dev}

# Admin Configuration
admin:
  discord-ids: "606162661184372736"  # k1le (comma-separated for multiple admins)

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: mappings,health,info
  endpoint:
    mappings:
      enabled: true
